# Generated by Django 3.1.1 on 2020-09-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_auto_20200929_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='blog',
        ),
    ]
