# Generated by Django 3.1.1 on 2020-09-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_auto_20200929_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blog',
            new_name='post',
        ),
    ]
